version: '3.8'

services:
  pentest-lab:
    build: .
    container_name: stealth-pentest-lab
    hostname: generic-ubuntu-server
    privileged: true
    network_mode: bridge  # Changed from host to bridge for better compatibility
    volumes:
      - ./data:/home/pentester/data
      - ./logs:/home/pentester/logs
      - ./reports:/home/pentester/reports
    ports:
      - "4444:4444"  # Metasploit listener
      - "8080:8080"  # Web tools
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TERM=xterm-256color
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
